M48
; DRILL file {KiCad (6.0.6)} date Thu 28 Jul 2022 10:42:37 PM PDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-28T22:42:37-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.702
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.429
%
G90
G05
T1
X84.5Y-42.8
X84.5Y-61.4
X95.5Y-42.8
X95.5Y-61.4
T2
X85.05Y-65.15
X89.95Y-36.85
X90.05Y-67.35
X94.95Y-39.05
T3
X90.0Y-42.8
X90.0Y-61.4
T0
M30
